name : Build & Deploy
on:
  push:
      branches:
             - main 
        
 
env :
  CI: false
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v2

      - name: Run a one-line script
      - run: echo Project Build

      - name: Run a multi-line script
      - run: | 
              echo Add other action to build,
              echo test,and deploy project 
            




    
  
